cook: remake copy_generic_files()/copy_generic_stuff() logic; change build dep installation (AUTO_COOK isn't work now) with tazpkg cookmode; improve mk_pkg_receipt(), copy(); update 'cook package --pack'; add docs about copy(); lighttpd/index.cgi: summary on unpackaged files; tiny edits on lighttpd/cooker.css and modules/compressor.

diff --git a/cook b/cook
--- a/cook
+++ b/cook
@@ -301,7 +301,7 @@ extract_source() {
 		*.tar.lzma)             tar   -xaf    $SRC/$TARBALL ;;
 		*.tar.lz|*.tlz)         lzip  -d    < $SRC/$TARBALL | tar -xf - 2>/dev/null ;;
 		*.tar)                  tar   -xf     $SRC/$TARBALL ;;
-		*.zip|*.xpi)            unzip -o      $SRC/$TARBALL 2>/dev/null ;;
+		*.zip|*.xpi)            unzip -o      $SRC/$TARBALL 2>/dev/null >&2;;
 		*.xz)                   unxz  -c      $SRC/$TARBALL | tar -xf - || \
 		                        tar   -xf     $SRC/$TARBALL 2>/dev/null;;
 		*.7z)                   7zr    x      $SRC/$TARBALL 2>/dev/null >&2 ;;
@@ -352,7 +352,7 @@ summary() {
 	_ 'Host arch   : %s' "$ARCH"
 
 	separator -
-	_ ' # : Packed : Compressed : Files : Package name'
+	_ ' # :  Packed : Compressed : Files : Package name'
 	separator -
 	pkgi=1
 	for i in $PACKAGE $SPLIT; do
@@ -360,7 +360,7 @@ summary() {
 		pkgname="$i-$VERSION.tazpkg"
 		size=$(ls -lh $PKGS/$pkgname | awk '{print $5}')
 		files=$(wc -l < $WOK/$pkg/taz/$i-$VERSION/files.list)
-		printf "%2d : %6s : %10s : %5s : %s\n" "$pkgi" "$fs" "$size" "$files" "$pkgname"
+		printf "%2d : %7s : %10s : %5s : %s\n" "$pkgi" "$fs" "$size" "$files" "$pkgname"
 		pkgi=$((pkgi + 1))
 	done
 	separator
@@ -406,17 +406,22 @@ scopy() {
 }
 
 
-# Copy all generic files (locale, pixmaps, .desktop). We use standard paths,
-# so some packages need to copy these files with the receipt and genpkg_rules.
+# Copy all generic files (locale, pixmaps, .desktop) from $install to $fs.
+# We use standard paths, so some packages need to copy these files with the
+# receipt and genpkg_rules.
+# This function executes inside the packaging process, before compressor call.
 
 copy_generic_files() {
+	# Proceed only for "main" package (for v2), and for any packages (v1)
+	[ "$pkg" == "$PACKAGE" ] || return 0
+
 	# $LOCALE is set in cook.conf
 	if [ -n "$LOCALE" -a -z "$WANTED" ]; then
 		if [ -d "$install/usr/share/locale" ]; then
-			mkdir -p $fs/usr/share/locale
+			mkdir -p "$fs/usr/share/locale"
 			for i in $LOCALE; do
 				if [ -d  "$install/usr/share/locale/$i" ]; then
-					scopy $install/usr/share/locale/$i $fs/usr/share/locale
+					cp -a $install/usr/share/locale/$i $fs/usr/share/locale
 				fi
 			done
 		fi
@@ -425,43 +430,49 @@ copy_generic_files() {
 	# Generic pixmaps copy can be disabled with COOKOPTS="!pixmaps" (or GENERIC_PIXMAPS="no")
 	if [ "${COOKOPTS/!pixmaps/}" == "$COOKOPTS" -a "$GENERIC_PIXMAPS" != 'no' ]; then
 		if [ -d "$install/usr/share/pixmaps" ]; then
-			mkdir -p $fs/usr/share/pixmaps
+			mkdir -p "$fs/usr/share/pixmaps"
 			for i in png xpm; do
 				[ -f "$install/usr/share/pixmaps/$PACKAGE.$i" ] &&
-				scopy $install/usr/share/pixmaps/$PACKAGE.$i $fs/usr/share/pixmaps
+				cp -a $install/usr/share/pixmaps/$PACKAGE.$i $fs/usr/share/pixmaps
 			done
-		fi
-
-		# Custom or homemade PNG pixmap can be in stuff.
-		if [ -f "$stuff/$PACKAGE.png" ]; then
-			mkdir -p $fs/usr/share/pixmaps
-			scopy $stuff/$PACKAGE.png $fs/usr/share/pixmaps
 		fi
 	fi
 
 	# Desktop entry (.desktop).
 	# Generic desktop entry copy can be disabled with COOKOPTS="!menus" (or GENERIC_MENUS="no")
 	if [ "${COOKOPTS/!menus/}" == "$COOKOPTS" -a "$GENERIC_MENUS" != 'no' ]; then
-		if [ -d "$install/usr/share/applications" ] && [ -z "$WANTED" ]; then
-			mkdir -p $fs/usr/share
-			scopy $install/usr/share/applications $fs/usr/share
+		if [ -d "$install/usr/share/applications" -a -z "$WANTED" ]; then
+			mkdir -p "$fs/usr/share"
+			cp -a $install/usr/share/applications $fs/usr/share
 		fi
+	fi
+}
+
+
+# Copy pixmaps, desktop files and licenses from $stuff to $install.
+# This function executes after the main compile_rules() is done.
+
+copy_generic_stuff() {
+	# Custom or homemade PNG pixmap can be in stuff.
+	if [ -f "$stuff/$PACKAGE.png" ]; then
+		mkdir -p $install/usr/share/pixmaps
+		cp $stuff/$PACKAGE.png $install/usr/share/pixmaps
 	fi
 
 	# Homemade desktop file(s) can be in stuff.
 	if [ -d "$stuff/applications" ]; then
-		mkdir -p $fs/usr/share
-		scopy $stuff/applications $fs/usr/share
+		mkdir -p $install/usr/share
+		cp $stuff/applications $install/usr/share
 	fi
 	if [ -f "$stuff/$PACKAGE.desktop" ]; then
-		mkdir -p $fs/usr/share/applications
-		scopy $stuff/$PACKAGE.desktop $fs/usr/share/applications
+		mkdir -p $install/usr/share/applications
+		cp $stuff/$PACKAGE.desktop $install/usr/share/applications
 	fi
 
 	# Add custom licenses
 	if [ -d "$stuff/licenses" ]; then
-		mkdir -p $fs/usr/share/licenses
-		scopy $stuff/licenses $fs/usr/share/licenses/$PACKAGE
+		mkdir -p $install/usr/share/licenses
+		cp $stuff/licenses $install/usr/share/licenses/$PACKAGE
 	fi
 }
 
@@ -532,9 +543,12 @@ patchit() {
 
 	while read i; do
 		[ -f "$src/done.$i" ] && continue
-		patch -p1 -i $stuff/patches/$i
+		newline
+		_ 'Applying patch %s' "$i"
+		patch -p1 -i $stuff/patches/$i | sed 's|^|  |'
 		touch $src/done.$i
 	done < $stuff/patches/series
+	newline
 }
 
 
@@ -627,89 +641,83 @@ cookit() {
 
 	# Check for build deps and handle implicit depends of *-dev packages
 	# (ex: libusb-dev :: libusb).
-	rm -f $CACHE/installed.local $CACHE/installed.web $CACHE/missing.dep
-	touch $CACHE/installed.local $CACHE/installed.web
+#	rm -f $CACHE/installed.local $CACHE/installed.web $CACHE/missing.dep
+#	touch $CACHE/installed.local $CACHE/installed.web
 	[ -n "$BUILD_DEPENDS" ] && _ 'Checking build dependencies...'
 	[ -n "$root" ] && _ 'Using packages DB: %s' "$root$DB"
-	for dep in $BUILD_DEPENDS; do
-		implicit="${dep%-dev}"; [ "$implicit" == "$dep" ] && implicit=''
-		for i in $dep $implicit; do
-#			echo "i='$i'"
-			# Check if package already installed
-			[ -f "$root$INSTALLED/$i/receipt" ] && continue
 
-			# Try local package first.
-			namever=$(awk -F$'\t' -vpkg="$i" '{
-				# if package-name or provided-package-name matched
-				if (index(" " $1 " " $10 " ", " " pkg " ")) { printf("%s-%s", $1, $2); exit; }
-			}' "$PKGS/packages.info")		# <namever> = <package_name>-<package_version>
+	for action in check install; do
+		for dep in $BUILD_DEPENDS; do
+			implicit="${dep%-dev}"; [ "$implicit" == "$dep" ] && implicit=''
+			for i in $dep $implicit; do
+				# Skip if package already installed
+				[ -f "$root$INSTALLED/$i/receipt" ] && continue
 
-			debug "bdep: $i name-version: $namever"
-
-			# If local package available
-			[ -f "$PKGS/$namever$arch.tazpkg" ] &&
-				echo "$namever$arch.tazpkg" >> $CACHE/installed.local && continue
-
-			# If package exists in wok but not built
-			[ -d "$WOK/$i" ] &&
-				_ 'Missing dep (wok/pkg): %s' "$i $vers" &&
-				echo $i >> $CACHE/missing.dep && continue
-
-			# If package available on the mirror
-			[ -n "$(awk -F$'\t' -vi="$i" '$1==i{print $1}' "$root$DB/packages.info")" ] &&
-				echo $i >> $CACHE/installed.web && continue
-
-			# Give up; skip error for implicit dependency: in some cases
-			# implicit doesn't exist, ex: libboost-dev exists but not libboost.
-			[ "$i" == "$dep" ] && die 'ERROR: unknown dep "%s"' "$i"
+				case $action in
+					check)
+						# Search for local package or local provided-package
+						name=$(awk -F$'\t' -vpkg="$i" '{
+						if (index(" " $1 " " $10 " ", " " pkg " ")) {print $1; exit}
+						}' "$PKGS/packages.info")
+						if [ -z "$name" ]; then
+							# Search for package in mirror
+							name="$(awk -F$'\t' -vi="$i" '$1==i{print $1; exit}' "$root$DB/packages.info")"
+							[ -z "$name" -a "$i" == "$dep" ] && die 'ERROR: unknown dep "%s"' "$i"
+						fi
+						;;
+					install)
+						tazpkg get-install $i --root=$root --local --quiet --cookmode || { broken; exit 1; }
+						;;
+				esac
+			done
 		done
 	done
 
-	# Get the list of installed packages
-	cd $root$INSTALLED; ls -1 > $CACHE/installed.list
-
-	# Have we a missing build dep to cook?
-	if [ -s "$CACHE/missing.dep" ] && [ -n "$AUTO_COOK" ]; then
-		_ 'Auto cook config is set: %s' "$AUTO_COOK"
-		cp -f $LOGS/$PACKAGE.log $LOGS/$PACKAGE.log.$$
-		for i in $(uniq $CACHE/missing.dep); do
-			(_ 'Building dep (wok/pkg)    : %s' "$i $vers") | \
-				tee -a $LOGS/$PACKAGE.log.$$
-			# programmers: next two messages are exact copy from remove_deps()
-			togrep1=$(_n 'Build dependencies to remove:')
-			togrep2=$(_n 'Removing:')
-			cook $i || (_ "ERROR: can't cook dep \"%s\"" "$i" && newline && \
-				fgrep $togrep1 $LOGS/$i.log && \
-				fgrep $togrep2 $LOGS/$i.log && newline) | \
-				tee -a $LOGS/$PACKAGE.log.$$ && break
-		done
-		rm -f $CACHE/missing.dep
-		mv  $LOGS/$PACKAGE.log.$$ $LOGS/$PACKAGE.log
-	fi
-
-	# QA: Exit on missing dep errors. We exit in both cases, if AUTO_COOK
-	# is enabled and cook fails we have ERROR in log, if no auto cook we have
-	# missing dep in cached file.
-	lerror=$(_n 'ERROR')
-	if fgrep -q ^$lerror $LOGS/$pkg.log || [ -s "$CACHE/missing.dep" ]; then
-		[ -s "$CACHE/missing.dep" ] && nb=$(wc -l < $CACHE/missing.dep)
-		_p 'ERROR: missing %d dependency' 'ERROR: missing %d dependencies' "$nb" "$nb"
-		broken; exit 1
-	fi
-
-	# Install local packages: package-version$arch
-	cd $PKGS
-	for i in $(uniq $CACHE/installed.local); do
-		# _ 'Installing dep (pkg/local): %s' "$i"
-		tazpkg install $i --root=$root --local --quiet --cookmode
-	done
-
-	# Install web or cached packages (if mirror is set to $PKGS we only
-	# use local packages).
-	for i in $(uniq $CACHE/installed.web); do
-		# _ 'Installing dep (web/cache): %s' "$i"
-		tazpkg get-install $i --root=$root --local --quiet --cookmode
-	done
+#	# Get the list of installed packages
+#	cd $root$INSTALLED; ls -1 > $CACHE/installed.list
+#
+#	# Have we a missing build dep to cook?
+#	if [ -s "$CACHE/missing.dep" ] && [ -n "$AUTO_COOK" ]; then
+#		_ 'Auto cook config is set: %s' "$AUTO_COOK"
+#		cp -f $LOGS/$PACKAGE.log $LOGS/$PACKAGE.log.$$
+#		for i in $(uniq $CACHE/missing.dep); do
+#			(_ 'Building dep (wok/pkg)    : %s' "$i $vers") | \
+#				tee -a $LOGS/$PACKAGE.log.$$
+#			# programmers: next two messages are exact copy from remove_deps()
+#			togrep1=$(_n 'Build dependencies to remove:')
+#			togrep2=$(_n 'Removing:')
+#			cook $i || (_ "ERROR: can't cook dep \"%s\"" "$i" && newline && \
+#				fgrep $togrep1 $LOGS/$i.log && \
+#				fgrep $togrep2 $LOGS/$i.log && newline) | \
+#				tee -a $LOGS/$PACKAGE.log.$$ && break
+#		done
+#		rm -f $CACHE/missing.dep
+#		mv  $LOGS/$PACKAGE.log.$$ $LOGS/$PACKAGE.log
+#	fi
+#
+#	# QA: Exit on missing dep errors. We exit in both cases, if AUTO_COOK
+#	# is enabled and cook fails we have ERROR in log, if no auto cook we have
+#	# missing dep in cached file.
+#	lerror=$(_n 'ERROR')
+#	if fgrep -q ^$lerror $LOGS/$pkg.log || [ -s "$CACHE/missing.dep" ]; then
+#		[ -s "$CACHE/missing.dep" ] && nb=$(wc -l < $CACHE/missing.dep)
+#		_p 'ERROR: missing %d dependency' 'ERROR: missing %d dependencies' "$nb" "$nb"
+#		broken; exit 1
+#	fi
+#
+#	# Install local packages: package-version$arch
+#	cd $PKGS
+#	for i in $(uniq $CACHE/installed.local); do
+#		# _ 'Installing dep (pkg/local): %s' "$i"
+#		tazpkg install $i --root=$root --local --quiet --cookmode
+#	done
+#
+#	# Install web or cached packages (if mirror is set to $PKGS we only
+#	# use local packages).
+#	for i in $(uniq $CACHE/installed.web); do
+#		# _ 'Installing dep (web/cache): %s' "$i"
+#		tazpkg get-install $i --root=$root --local --quiet --cookmode
+#	done
 
 	update_installed_cook_diff
 
@@ -775,6 +783,8 @@ cookit() {
 		mkdir -p $install
 	fi
 
+	copy_generic_stuff
+
 	# Actions to do after compiling the package
 	# Skip all for split packages (already done in main package)
 	if [ -z "$WANTED" ]; then
@@ -824,15 +834,26 @@ mk_pkg_receipt() {
 	[ "${signature:0:1}" == '#' ] || signature='# SliTaz package receipt.'
 
 	save_PACKAGE="$PACKAGE"; save_DEPENDS="$DEPENDS"; save_PROVIDE="$PROVIDE"
+	save_SUGGESTED="$SUGGESTED"; save_TAZPANEL_DAEMON="$TAZPANEL_DAEMON"
 	unset_receipt
 	. "$orig_receipt"
 	PACKAGE="$save_PACKAGE"; DEPENDS="$save_DEPENDS"; PROVIDE="$save_PROVIDE"
+	SUGGESTED="$save_SUGGESTED"; TAZPANEL_DAEMON="$save_TAZPANEL_DAEMON"
 
 	# Manage split packages
 	SPLIT=" $SPLIT "
 	if [ "$SPLIT" != '  ' -a "${SPLIT/ $PACKAGE /}" != "$SPLIT" ]; then
 		# For packages with empty $DEPENDS
-		[ -n "$DEPENDS" ] || DEPENDS="$pkg"
+		if [ -z "$DEPENDS" ]; then
+			case $PACKAGE in
+				*-dev)
+					# main package and all the split packages but this *-dev itself
+					DEPENDS=$(echo "$pkg $SPLIT " | sed "s| $PACKAGE | |; s| *$||") ;;
+				*)
+					# main package
+					DEPENDS="$pkg" ;;
+			esac
+		fi
 
 		# Default $CAT
 		[ -z "$CAT" ] &&
@@ -859,23 +880,24 @@ WEB_SITE="$WEB_SITE"
 EOF
 
 	# Optional variables
-	[ -n "$TAGS" ]    && echo "TAGS=\"$TAGS\""
-	[ -n "$DEPENDS" ] && echo "DEPENDS=\"$DEPENDS\"" | tr -ds '\t' ' '
-	[ -n "$PROVIDE" ] && echo "PROVIDE=\"$PROVIDE\""
-	[ -n "$CONFIG_FILES" ] && echo "CONFIG_FILES=\"$CONFIG_FILES\""
+	[ -n "$TAGS" ]    && echo "TAGS=\"$TAGS\"" | tr -ds '\t' ' '
+	[ -n "${DEPENDS# }" ] && echo "DEPENDS=\"$DEPENDS\"" | tr -ds '\t' ' '
+	[ -n "$PROVIDE" ] && echo "PROVIDE=\"$PROVIDE\"" | tr -ds '\t' ' '
+	[ -n "$CONFIG_FILES" ] && echo "CONFIG_FILES=\"$CONFIG_FILES\"" | tr -ds '\t' ' '
+	[ -n "$DATABASE_FILES" ] && echo "DATABASE_FILES=\"$DATABASE_FILES\""
+	[ -n "$TAZPANEL_DAEMON" ] && echo "TAZPANEL_DAEMON=\"$TAZPANEL_DAEMON\""
 
 	# Extract {pre,post}_{install,remove} functions;
-	# post_install_gtk_() will be copied as post_install() for gtk+ package
+	# post_install()      will be copied for both main and all the split packages
+	# post_install_gtk_() will be copied as post_install() for gtk+ package only
 	#
 	# restricted name (gtk+ -> gtk_; acl-dev -> acl_dev)
 	rname=$(echo -n $PACKAGE | tr -c 'a-zA-Z0-9' '_')
 	for i in pre post; do
 		for j in install remove; do
-			if grep -q "^${i}_${j}_$rname()" "$orig_receipt"; then
-				echo
-				sed "/^${i}_${j}_$rname()/,/^}/!d" "$orig_receipt" | \
+			sed "/^${i}_${j}()/,/^}/!d" "$orig_receipt"
+			sed "/^${i}_${j}_$rname()/,/^}/!d" "$orig_receipt" | \
 				sed "s|^${i}_${j}_$rname()|${i}_${j}()|"
-			fi
 		done
 	done
 }
@@ -907,6 +929,7 @@ packit() {
 
 	# Check CONFIG_FILES
 	if [ -n "$CONFIG_FILES" ]; then
+		unset IFS
 		for i in $CONFIG_FILES; do
 			if [ ! -e $fs$i ]; then
 				case $i in
@@ -1059,7 +1082,7 @@ packall() {
 	set_paths
 	if head -n1 "$pkgdir/receipt" | fgrep -q 'v2'; then
 		for i in $PACKAGE $SPLIT; do
-			unset DEPENDS CAT CONFIG_FILES
+			unset TAGS DEPENDS CAT CONFIG_FILES PROVIDE DATABASE_FILES TAZPANEL_DAEMON
 			packit $i
 		done
 	else
@@ -1277,10 +1300,9 @@ cook_copy_folders() {
 
 copy() {
 	action 'Copying folders and files...'
-	cd $install
-	local i j filelist=$(mktemp) tmplist=$(mktemp)
+	local i j filelist=$(mktemp)
 	IFS=$'\n'
-	find ! -type d | sed 's|\.||' > $filelist
+	cd $install; find ! -type d | sed 's|\.||' > $filelist
 	for i in $@; do
 		case $i in
 			@std)
@@ -1291,41 +1313,37 @@ copy() {
 					/\/share\/man\//d; /\/share\/doc\//d; /\/share\/gtk-doc\//d; /\/share\/info\//d;
 					/\/share\/devhelp\//d; /\/share\/locale\//d;
 					/\/share\/bash-completion\//d; /\/lib\/systemd\//d;
-					' $filelist > $tmplist
-				while read j; do
-					mkdir -p $fs$(dirname $j)
-					scopy $install$j $fs$(dirname $j)
-				done < $tmplist
+					' $filelist
 				;;
 			@dev)
 				# Copy "developer files"
 				sed -n '/\.h$/p; /\.hxx$/p; /\.a$/p; /\.la$/p; /\.pc$/p; /bin\/.*-config$/p;
 					/\.m4$/p; /\.gir$/p; /\.typelib$/p; /\.vapi$/p; /\.deps$/p; /\.cmake$/p;
 					/\/include\//p;
-					' $filelist | \
-				while read j; do
-					mkdir -p $fs$(dirname $j)
-					scopy $install$j $fs$(dirname $j)
-				done
+					' $filelist
 				;;
 			*/)
-				# Copy specified folders
-				for j in $(find . -name ${i%/} -type d); do
-					mkdir -p $fs$(dirname ${j#.})
-					cp -a $j $fs$(dirname ${j#.})
-				done
+				# Copy specified folders.
+				i="${i%/}"
+				find -type d -path "*/${i#/}" | sed 's|^.||'
 				;;
 			*)
-				# Copy specified files
-				for j in $(find . -name $i ! -type d); do
-					mkdir -p $fs$(dirname ${j#.})
-					scopy $j $fs$(dirname ${j#.})
-				done
+				# Copy specified files.
+				find ! -type d -path "*/${i#/}" | sed 's|^.||'
 				;;
-		esac
+		esac | sort -u | \
+		while read j; do
+			mkdir -p $fs$(dirname "$j")
+			if [ -d "$install$j" ]; then
+				cp -a "$install$j" $fs$(dirname "$j")
+			else
+				scopy "$install$j" $fs$(dirname "$j")
+			fi
+		done
 	done
 	cd - >/dev/null
-	rm $filelist $tmplist
+	unset IFS
+	rm $filelist
 	status
 }
 
@@ -1760,7 +1778,7 @@ case "$1" in
 				[ -d $WOK/$pkg/taz ] || die 'Need to build "%s"' "$pkg"
 				rm -rf $WOK/$pkg/taz
 				[ -f $LOGS/$pkg-pack.log ] && rm -rf $LOGS/$pkg-pack.log
-				packit 2>&1 | tee -a $LOGS/$pkg-pack.log
+				packall 2>&1 | tee -a $LOGS/$pkg-pack.log
 				clean_log
 				rm -f $command
 				exit 0 ;;
