cook: add support for git branch so aufs builds

diff --git a/cook b/cook
--- a/cook
+++ b/cook
@@ -196,7 +196,12 @@ get_source() {
 			tarball=$pkgsrc.tar.bz2
 			gettext -e "Getting source from Git...\n"
 			echo "URL: $url"
-			git clone $url $pkgsrc || (echo "ERROR: git clone $url" && exit 1)
+			if [ "$BRANCH" ]; then
+				git clone $url $pkgsrc || (echo "ERROR: git clone $url" && exit 1)
+				cd $pkgsrc && git checkout $BRANCH && cd ..
+			else
+				git clone $url $pkgsrc || (echo "ERROR: git clone $url" && exit 1)
+			fi
 			gettext "Creating tarball: "; echo "$tarball"
 			tar cjf $tarball $pkgsrc || exit 1
 			mv $tarball $SRC && rm -rf $pkgsrc ;;
