Handle CROSS_BUGS (will move the few CROSS var to it so all cross configs are prefixed with CROSS_ in cook)

diff --git a/cook b/cook
--- a/cook
+++ b/cook
@@ -141,7 +141,7 @@ receipt_quality() {
 # Executed before sourcing a receipt.
 unset_receipt() {
 	unset DEPENDS BUILD_DEPENDS WANTED EXTRAVERSION WGET_URL PROVIDE TARBALL
-	unset HOST_ARCH CROSS_BUG
+	unset HOST_ARCH CROSS_BUGS
 }
 
 # Paths used in receipt and by cook itself.
@@ -426,9 +426,11 @@ cookit() {
 	separator
 	set_paths
 
-	# Handle cross compilation
+	# Handle cross compilation.
 	if [ "$HOST_ARCH" ] && [ ! $(echo "$HOST_ARCH" | fgrep $ARCH) ]; then
-		echo "ERROR: This package dont build on: $ARCH" && exit 1
+		echo "ERROR: This package dont cook or is not include in: $ARCH"
+		[ "$CROSS_BUGS" ] && echo "Bug: $CROSS_BUGS"
+		exit 1
 	fi
 	case "$ARCH" in
 		arm|x86_64)
